"""
Recover all 17 Block-Man rooms straight out of the game executable.

Run tools/extract/depklite.py on BMAN1.EXE first, with decryption enabled -
that detail matters more than anything else here. PKLITE's encrypted and
unencrypted modes produce output of identical length that both terminate
cleanly, so size alone cannot tell them apart. Decompressing without
decryption yields plausible-looking bytes that are actually garbage: no
`int 21h` anywhere and not one `push bp; mov bp,sp` in 124 KB.

With that fixed, the level table sits in the clear at 0x1aeb2:

    644 records of 20 bytes = 23 screens x 28 records
    each record is a length byte 0x13 (= 19) followed by 19 tiles

The records are COLUMNS, not rows. Transposed, each screen is 28 wide by 19
tall, which is exactly the 556x342 playfield at the game's 20x18 pixel tiles.

    screens  0..16   levels A..Q
    screens 17..22   the six skits

Tiles:

    .   outside the cavern      *   brick wall
    (space) open interior       T   wall torch (decorative, solid)
    O   movable block           $   the exit doorway
    <   Block-Man, facing left  >   Block-Man, facing right

Verified against published screenshots: screen 1 reproduces Level B, screen 2
Level C and screen 3 Level D, block for block.

    python tools/extract/from_exe.py BMAN1.EXE.dep
"""
import sys

TABLE_ROWS = 644
SCREEN_RECS = 28
REC_LEN = 20
ROW_LEN = 19
LEVEL_COUNT = 17

GLYPHS = set(' .*$<>TO')


def find_table(data: bytes) -> int:
    """Locate the run of 20-byte records whose length byte is 0x13."""
    hits = [
        i for i in range(len(data) - REC_LEN)
        if data[i] == ROW_LEN and all(chr(c) in GLYPHS for c in data[i + 1:i + REC_LEN])
    ]
    run_start, run_len, best = None, 0, None
    k = 0
    while k < len(hits) - 1:
        if hits[k + 1] - hits[k] == REC_LEN:
            j = k
            while j < len(hits) - 1 and hits[j + 1] - hits[j] == REC_LEN:
                j += 1
            if j - k + 1 > run_len:
                run_len, run_start = j - k + 1, hits[k]
            k = j
            continue
        k += 1
    if run_start is None or run_len < TABLE_ROWS:
        raise SystemExit(f'level table not found (longest run {run_len} records)')
    return run_start


def screens(data: bytes, base: int):
    """Yield each screen as 19 rows of 28 characters, already transposed."""
    recs = [
        data[base + i * REC_LEN + 1:base + i * REC_LEN + REC_LEN].decode('latin1')
        for i in range(TABLE_ROWS)
    ]
    for s in range(TABLE_ROWS // SCREEN_RECS):
        cols = recs[s * SCREEN_RECS:(s + 1) * SCREEN_RECS]
        yield [''.join(col[y] for col in cols) for y in range(ROW_LEN)]


def to_level(grid):
    """Convert one screen to our tile alphabet, trimmed to the cavern."""
    start = None
    facing = 'left'
    out = []
    for y, row in enumerate(grid):
        line = []
        for x, ch in enumerate(row):
            if ch in '<>':
                start = (x, y)
                facing = 'left' if ch == '<' else 'right'
                line.append('.')
            elif ch == 'O':
                line.append('o')
            elif ch == '$':
                line.append('D')
            elif ch == ' ':
                line.append('.')
            else:
                # '.', '*' and the decorative torch are all solid.
                line.append('#')
        out.append(''.join(line))
    if start is None:
        return None

    keep_r = [y for y, r in enumerate(out) if set(r) != {'#'}]
    r0, r1 = keep_r[0], keep_r[-1]
    keep_c = [x for x in range(len(out[0])) if any(out[y][x] != '#' for y in range(r0, r1 + 1))]
    c0, c1 = keep_c[0], keep_c[-1]
    rows = [r[c0:c1 + 1] for r in out[r0:r1 + 1]]
    return rows, (start[0] - c0, start[1] - r0), facing


if __name__ == '__main__':
    data = open(sys.argv[1], 'rb').read()
    base = find_table(data)
    sys.stderr.write(f'level table at 0x{base:05x}\n')

    letters = [chr(ord('A') + i) for i in range(LEVEL_COUNT)]
    out = []
    out.append('// AUTO-GENERATED by tools/extract/from_exe.py - do not edit by hand.')
    out.append('//')
    out.append('// The 17 authentic Block-Man rooms, lettered A-Q, read directly out of the')
    out.append('// 1993 Soleau Software executable. The level table is stored column-major')
    out.append('// as 23 screens of 28 records, each record a length byte followed by 19')
    out.append('// tiles; transposed, every screen is 28 wide by 19 tall. Screens 17-22 are')
    out.append('// the six skits and are not levels.')
    out.append('//')
    out.append('// Cross-checked against published screenshots: rooms B, C and D match')
    out.append('// block for block.')
    out.append('//')
    out.append('// Legend:  # wall   o block   D exit door   . empty')
    out.append('')
    out.append("import type { LevelDef } from '../core/types';")
    out.append('')
    out.append('export const BLOCKMAN_LEVELS: LevelDef[] = [')

    for i, grid in enumerate(screens(data, base)):
        if i >= LEVEL_COUNT:
            break
        res = to_level(grid)
        if not res:
            raise SystemExit(f'screen {i} has no start marker')
        rows, (sx, sy), facing = res
        out.append('  {')
        out.append(f"    name: 'Room {letters[i]}',")
        out.append(f"    start: {{ x: {sx}, y: {sy}, facing: '{facing}' }},")
        out.append('    rows: [')
        for r in rows:
            out.append(f'      {r!r},'.replace("'", '"'))
        out.append('    ],')
        out.append('  },')
        sys.stderr.write(
            f'  Room {letters[i]}: {len(rows[0])}x{len(rows)} '
            f'start=({sx},{sy}) {facing} blocks={sum(r.count("o") for r in rows)}\n'
        )

    out.append('];')
    out.append('')
    sys.stdout.write('\n'.join(out))
