// AUTO-GENERATED by tools/bm2-levels.mjs - do not edit by hand.
//
// ORIGINAL levels in the style of Block-Man 2, NOT Soleau layouts.
// Block-Man 2's own room data is obfuscated inside its executable and its
// levels scroll, so they cannot be recovered from screenshots the way
// Block-Man 1's rooms were. See tools/extract/README.md.
//
// Legend:  # wall   o block   * jewel   D exit door   . empty

import type { LevelDef } from '../core/types';

export const BLOCKMAN2_LEVELS: LevelDef[] = [
  {
    name: "A Handful of Jewels",
    start: { x: 11, y: 3, facing: 'left' },
    rows: [
      "#############",
      "#...........#",
      "#...........#",
      "#D..*....*..#",
      "#############",
    ],
  },
  {
    name: "Up on the Ledge",
    start: { x: 11, y: 3, facing: 'left' },
    rows: [
      "##############",
      "#......*.....#",
      "#....####....#",
      "#D.......o...#",
      "##############",
    ],
  },
  {
    name: "Over the Step",
    start: { x: 11, y: 4, facing: 'left' },
    rows: [
      "##############",
      "#............#",
      "#............#",
      "#.....*......#",
      "#D..o.##.....#",
      "##############",
    ],
  },
  {
    name: "The Split Shelf",
    start: { x: 13, y: 3, facing: 'left' },
    rows: [
      "################",
      "#..............#",
      "#....*....*....#",
      "#D..###..###...#",
      "################",
    ],
  },
  {
    name: "Carry It Over",
    start: { x: 11, y: 4, facing: 'left' },
    rows: [
      "###############",
      "#.............#",
      "#.....*.......#",
      "#.....#.......#",
      "#D....#...o...#",
      "###############",
    ],
  },
  {
    name: "The Long Gallery",
    start: { x: 12, y: 4, facing: 'left' },
    rows: [
      "##################",
      "#................#",
      "#.....*..........#",
      "#.....#.......*..#",
      "#D....#...o...#..#",
      "##################",
    ],
  },
];
