/**
 * Authoring source for the Block-Man 2 campaign.
 *
 * These levels are ORIGINAL, not Soleau's. Block-Man 2's own room data sits in
 * its executable as 100 Pascal-string records of 256 bytes at 0x2fcf2 of the
 * decompressed image, but the contents are obfuscated and not yet decoded, and
 * its levels scroll so they cannot be read off screenshots the way Block-Man 1's
 * can. These are written in its style instead: collect every jewel, then leave.
 *
 *   node tools/bm2-levels.mjs > src/levels/blockman2.ts
 *
 * Legend:  # wall   o block   * jewel   D door   @ Block-Man   . empty
 */

const LEVELS = [
  {
    name: 'A Handful of Jewels',
    rows: [
      '#############',
      '#...........#',
      '#...........#',
      '#D..*....*.@#',
      '#############',
    ],
  },
  {
    name: 'Up on the Ledge',
    rows: [
      '##############',
      '#......*.....#',
      '#....####....#',
      '#D.......o.@.#',
      '##############',
    ],
  },
  {
    name: 'Over the Step',
    rows: [
      '##############',
      '#............#',
      '#............#',
      '#.....*......#',
      '#D..o.##...@.#',
      '##############',
    ],
  },
  {
    name: 'The Split Shelf',
    rows: [
      '################',
      '#..............#',
      '#....*....*....#',
      '#D..###..###.@.#',
      '################',
    ],
  },
  {
    name: 'Carry It Over',
    rows: [
      '###############',
      '#.............#',
      '#.....*.......#',
      '#.....#.......#',
      '#D....#...o@..#',
      '###############',
    ],
  },
  {
    name: 'The Long Gallery',
    rows: [
      '##################',
      '#................#',
      '#.....*..........#',
      '#.....#.......*..#',
      '#D....#...o.@.#..#',
      '##################',
    ],
  },
];

const out = [];
out.push('// AUTO-GENERATED by tools/bm2-levels.mjs - do not edit by hand.');
out.push('//');
out.push('// ORIGINAL levels in the style of Block-Man 2, NOT Soleau layouts.');
out.push("// Block-Man 2's own room data is obfuscated inside its executable and its");
out.push('// levels scroll, so they cannot be recovered from screenshots the way');
out.push("// Block-Man 1's rooms were. See tools/extract/README.md.");
out.push('//');
out.push('// Legend:  # wall   o block   * jewel   D exit door   . empty');
out.push('');
out.push("import type { LevelDef } from '../core/types';");
out.push('');
out.push('export const BLOCKMAN2_LEVELS: LevelDef[] = [');

for (const level of LEVELS) {
  let start = null;
  const rows = level.rows.map((row, y) => {
    const x = row.indexOf('@');
    if (x >= 0) start = { x, y };
    return row.replace('@', '.');
  });
  if (!start) throw new Error(`${level.name}: no @ start marker`);

  const doorX = rows.findIndex((r) => r.includes('D')) >= 0
    ? rows.map((r) => r.indexOf('D')).find((i) => i >= 0)
    : 0;
  const facing = doorX < start.x ? 'left' : 'right';

  const width = Math.max(...rows.map((r) => r.length));
  if (rows.some((r) => r.length !== width)) {
    throw new Error(`${level.name}: rows are not all ${width} wide`);
  }

  out.push('  {');
  out.push(`    name: ${JSON.stringify(level.name)},`);
  out.push(`    start: { x: ${start.x}, y: ${start.y}, facing: '${facing}' },`);
  out.push('    rows: [');
  for (const r of rows) out.push(`      ${JSON.stringify(r)},`);
  out.push('    ],');
  out.push('  },');
}

out.push('];');
out.push('');
process.stdout.write(out.join('\n'));
