import fs from 'node:fs';
const levels = JSON.parse(fs.readFileSync('parsed.json', 'utf8'));

const NAMES = [
  'First Steps', 'The Long Climb', 'Descent', 'Cathedral',
  'The Vault', 'Switchback', 'Undercroft', 'Spiral Tower',
  'Crossroads', 'The Great Hall', "Triangulos' Keep",
];

const lines = [];
lines.push('// AUTO-GENERATED by tools/import-levels.mjs — do not edit by hand.');
lines.push('// The 11 classic Block-Man chambers, recovered from the open-source');
lines.push('// Block Dude CE port of the original Soleau Software layouts.');
lines.push('//');
lines.push('// Legend:  # wall   o block   D exit door   . empty');
lines.push('');
lines.push("import type { LevelDef } from '../core/types';");
lines.push('');
lines.push('export const LEVELS: LevelDef[] = [');

for (const L of levels) {
  // Trim trailing all-empty rows (padding in the original C arrays).
  const rows = [...L.rows];
  while (rows.length > L.sy + 1 && /^\.*$/.test(rows[rows.length - 1])) rows.pop();

  const facing = L.door.x < L.sx ? 'left' : 'right';
  lines.push('  {');
  lines.push(`    name: ${JSON.stringify(NAMES[L.id] ?? `Chamber ${L.id + 1}`)},`);
  lines.push(`    start: { x: ${L.sx}, y: ${L.sy}, facing: '${facing}' },`);
  lines.push('    rows: [');
  for (const r of rows) lines.push(`      ${JSON.stringify(r)},`);
  lines.push('    ],');
  lines.push('  },');
}

lines.push('];');
lines.push('');
fs.writeFileSync('levels.ts', lines.join('\n'));
console.log('wrote levels.ts', fs.statSync('levels.ts').size, 'bytes');
